parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     wnc_soldier
    database_user:     root
    database_password: lukasz.123

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    contact_email:     shmirahproject@gmail.com

    liip_vie.use_coffee: false
    # a little hack to avoid errors on missing node/coffescript.
    # remove -disabled if you want coffee.
    coffee.extension: "\.coffee-disabled$"
    coffee.bin: ''
    coffee.node: ''
    
    locales: [en, il]